name: book-tests

on:
  workflow_call:
    inputs:
      toolchain:
        description: "Rust toolchain to use"
        type: string

concurrency:
  group: "book-tests:${{ github.workflow }}:${{ github.ref }}"

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  book-setup:
    uses: ./.github/workflows/book-setup.yml
    with:
      toolchain: ${{ inputs.toolchain }}

  test:
    needs: book-setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore book setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.book-setup.outputs.cache-path }}
          key: ${{ needs.book-setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Test examples in book
        run: just book-tests
