name: book-setup

on:
  workflow_call:
    inputs:
      toolchain:
        description: "Rust toolchain to use"
        type: string
    outputs:
      cache-path:
        description: "Path for restoring cache item"
        value: ${{ jobs.book-setup.outputs.cache-path }}
      cache-key:
        description: "Key for restoring cache item"
        value: ${{ jobs.book-setup.outputs.cache-key }}

concurrency:
  group: "book-setup:${{ github.workflow }}:${{ github.ref }}"

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      toolchain: ${{ inputs.toolchain }}

  book-setup:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.key.outputs.cache-path }}
      cache-key: ${{ steps.key.outputs.cache-key }}
    steps:
      # Checkout immediately so file hashing works
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Save cache path and key to output
        id: key
        env:
          CACHE_PATH: |
            ~/.cargo/
            target/
          CACHE_KEY: book-setup-${{ hashFiles('.github/workflows/book-setup.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}
        run: |
          {
            echo 'cache-path<<EOF'
            echo "$CACHE_PATH"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          {
            echo 'cache-key<<EOF'
            echo "$CACHE_KEY"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # If the item already exists, skip to end
      - name: Lookup cache
        id: lookup
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ steps.key.outputs.cache-path }} 
          key: ${{ steps.key.outputs.cache-key }}
          lookup-only: true

      - name: Install Rust toolchain
        if: steps.lookup.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Restore setup cache
        if: steps.lookup.outputs.cache-hit != 'true'
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup.outputs.cache-path }}
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Setup book
        if: steps.lookup.outputs.cache-hit != 'true'
        run: just setup-book

      - name: Save book setup cache
        if: steps.lookup.outputs.cache-hit != 'true'
        uses: actions/cache/save@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ steps.key.outputs.cache-path }} 
          key: ${{ steps.key.outputs.cache-key }}
