name: deploy-book

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"

jobs:
  get-toolchain:
    uses: ./.github/workflows/existing-toolchain.yml

  book-setup:
    needs: get-toolchain
    uses: ./.github/workflows/book-setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  book-tests:
    needs: get-toolchain
    uses: ./.github/workflows/book-tests.yml
    with:
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  deploy:
    needs: [get-toolchain, book-setup, book-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore book setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.book-setup.outputs.cache-path }}
          key: ${{ needs.book-setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Build book
        run: just book-build

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: 'book-output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
