name: Book Deploy
on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: &toolchain "nightly-2026-01-07"

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore setup cache
        uses: actions/cache/restore@v4
        id: setup-cache
        with:
          path: |
            ~/.cargo/
            target/
          key: setup-${{ hashFiles('justfile', 'Cargo.lock', 'rust-toolchain.toml') }}
          fail-on-cache-miss: true

      - name: Restore book setup cache
        id: book-setup-cache
        uses: actions/cache/restore@v4
        with:
          path: &cache_path |
            ~/.cargo/
            target/
          key: &cache_key book-${{ hashFiles('justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Setup book
        if: steps.book-setup-cache.outputs.cache-hit != 'true'
        run: just setup-book

      - name: Save book setup cache
        if: steps.book-setup-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: *cache_path
          key: *cache_key

      - name: Test examples in book
        run: just book-tests

      - name: Build book
        run: just book-build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book-output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
