name: Book Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"

jobs:
  book-setup:
    uses: ./.github/workflows/book-setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: &toolchain "nightly-2026-01-07"

  book-tests:
    uses: ./.github/workflows/book-tests.yml
    with:
      toolchain: *toolchain

  deploy:
    needs: [book-setup, book-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore book setup cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ needs.book-setup.outputs.cache-path }}
          key: ${{ needs.book-setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Build book
        run: just book-build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book-output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
