name: setup

on:
  workflow_call:
    inputs:
      toolchain:
        description: "Rust toolchain to use"
        type: string
    outputs:
      cache-path:
        description: "Path for restoring cache item"
        value: ${{ jobs.setup.outputs.cache-path }}
      cache-key:
        description: "Key for restoring cache item"
        value: ${{ jobs.setup.outputs.cache-key }}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.key.outputs.cache-path }}
      cache-key: ${{ steps.key.outputs.cache-key }}
    steps:
      # Checkout immediately so file hashing works
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save cache path and key to output
        id: key
        env:
          CACHE_PATH: |
            ~/.cargo/
            target/
          CACHE_KEY: setup-${{ hashFiles('.github/workflows/setup.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}
        run: |
          {
            echo 'cache-path<<EOF'
            echo "$CACHE_PATH"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          {
            echo 'cache-key<<EOF'
            echo "$CACHE_KEY"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # If the item already exists, skip to end
      - name: Lookup cache
        id: lookup
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.key.outputs.cache-path }}
          key: ${{ steps.key.outputs.cache-key }}
          lookup-only: true

      - name: Install Rust toolchain
        if: steps.lookup.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install `just`
        if: steps.lookup.outputs.cache-hit != 'true'
        run: cargo install just

      - name: Save cache
        if: steps.lookup.outputs.cache-hit != 'true'
        id: save
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.key.outputs.cache-path }}
          key: ${{ steps.key.outputs.cache-key }}
