name: tests-and-coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: &toolchain "nightly-2026-01-08"

  tests-and-coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: *toolchain
          components: clippy, rust-src

      - &checkout
        name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - &restore-setup
        name: Restore setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup.outputs.cache-path }}
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Cache tests and coverage setup
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            ~/.cargo/
            target/
          key: tests-and-coverage-${{ hashFiles('.github/workflows/tests-and-coverage.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Run tests and coverage
        run: just setup-coverage coverage-lcov

      - name: Coveralls upload
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2
        with:
          file: lcov.info
          format: lcov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  book-tests:
    uses: ./.github/workflows/book-tests.yml
    with:
      toolchain: *toolchain

  expansion-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: *toolchain

      - *checkout
      - *restore-setup

      - name: Cache expansion tests setup
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            ~/.cargo/
            target/
          key: expansion-tests-${{ hashFiles('.github/workflows/tests-and-coverage.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Expansion tests
        run: just setup-expansion expansion-tests

  check-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: *toolchain
          components: rustfmt

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just format-check

  clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: *toolchain
          components: clippy

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just clippy
