name: tests-and-coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: &toolchain "nightly-2026-01-07"

  tests-and-coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain
          components: clippy, rust-src

      - &checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - &restore-setup
        name: Restore setup cache
        uses: actions/cache/restore@v4
        id: setup-cache
        with:
          path: |
            ~/.cargo/
            target/
          key: setup-${{ hashFiles('justfile', 'Cargo.lock', 'rust-toolchain.toml') }}
          fail-on-cache-miss: true

      - name: Cache tests and coverage setup
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: tests-and-coverage-${{ hashFiles('justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Run tests and coverage
        run: just setup-coverage coverage-lcov

      - name: Coveralls upload
        uses: coverallsapp/github-action@v2.3.6
        with:
          file: lcov.info
          format: lcov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  expansion-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain

      - *checkout
      - *restore-setup

      - name: Cache expansion tests setup
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: expansion-tests-${{ hashFiles('justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Expansion tests
        run: just setup-expansion expansion-tests

  check-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain
          components: rustfmt

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just format-check

  clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: *toolchain
          components: clippy

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just clippy
