name: tests-and-coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"

env:
  RUSTUP_AUTO_INSTALL: "0"

jobs:
  get-toolchain:
    uses: ./.github/workflows/existing-toolchain.yml

  setup:
    needs: get-toolchain
    uses: ./.github/workflows/setup.yml
    with:
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  tests-and-coverage:
    needs: [get-toolchain, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}
          components: clippy, rust-src
          # For `no_std` build confirmation
          target: "x86_64-unknown-none"

      - &checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - &restore-setup
        name: Restore setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup.outputs.cache-path }}
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Cache tests and coverage setup
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            ~/.cargo/
            target/
          key: tests-and-coverage-${{ hashFiles('.github/workflows/tests-and-coverage.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Run tests and coverage
        run: just setup-test check-deps setup-coverage coverage-lcov build-no-std ''

      - name: Coveralls upload
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2
        with:
          file: lcov.info
          format: lcov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  get-msrv:
    needs: [setup]
    uses: ./.github/workflows/msrv.yml
    with:
      cache-path: ${{ needs.setup.outputs.cache-path }}
      cache-key: ${{ needs.setup.outputs.cache-key }}

  setup-msrv:
    needs: get-msrv
    uses: ./.github/workflows/setup.yml
    with:
      toolchain: ${{ needs.get-msrv.outputs.msrv }}

  test-msrv:
    needs: [get-msrv, setup-msrv]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-msrv.outputs.msrv }}
          # For `no_std` build confirmation
          target: "x86_64-unknown-none"

      - *checkout

      - name: Restore setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup-msrv.outputs.cache-path }}
          key: ${{ needs.setup-msrv.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Run tests
        env:
          RUSTUP_TOOLCHAIN: ${{ needs.get-msrv.outputs.msrv }}
        # cargo-deny@0.18.3 is the latest version to support rust versions prior to 1.88.0.
        # An alternate config is used due to newer keys not being supported.
        run: |
          cargo install --locked cargo-deny@0.18.3
          cargo deny check --config deny-0.18.3.toml licenses bans sources
          just test-toolchain '${{ needs.get-msrv.outputs.msrv }}'

  setup-stable:
    uses: ./.github/workflows/setup.yml
    with:
      toolchain: stable

  test-stable:
    needs: [setup-stable]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: stable
          # For `no_std` build confirmation
          target: "x86_64-unknown-none"

      - *checkout

      - name: Restore setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup-stable.outputs.cache-path }}
          key: ${{ needs.setup-stable.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Run tests
        env:
          RUSTUP_TOOLCHAIN: stable
        run: just setup-test check-deps test-toolchain stable

  setup-beta:
    uses: ./.github/workflows/setup.yml
    with:
      toolchain: beta

  test-beta:
    needs: [setup-beta]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: beta
          # For `no_std` build confirmation
          target: "x86_64-unknown-none"

      - *checkout

      - name: Restore setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.setup-beta.outputs.cache-path }}
          key: ${{ needs.setup-beta.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Run tests
        env:
          RUSTUP_TOOLCHAIN: beta
        run: just setup-test check-deps test-toolchain beta

  book-tests:
    needs: get-toolchain
    uses: ./.github/workflows/book-tests.yml
    with:
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  expansion-tests:
    needs: [get-toolchain, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

      - *checkout
      - *restore-setup

      - name: Cache expansion tests setup
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            ~/.cargo/
            target/
          key: expansion-tests-${{ hashFiles('.github/workflows/tests-and-coverage.yml', 'justfile', 'Cargo.lock', 'rust-toolchain.toml') }}

      - name: Expansion tests
        run: just setup-expansion expansion-tests

  check-format:
    needs: [get-toolchain, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}
          components: rustfmt

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just format-check

  clippy:
    needs: [get-toolchain, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}
          components: clippy

      - *checkout
      - *restore-setup

      - name: Check formatting
        run: just clippy
